CREATE TABLE IF NOT EXISTS `novel` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `nid` INTEGER UNIQUE NOT NULL,
    `title` TEXT NOT NULL,
    `author` TEXT NOT NULL,
    `ndate` TEXT NOT NULL,
    `ntype` TEXT NOT NULL,
    `link` TEXT NOT NULL,
    `size` INTEGER NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);