DROP TABLE IF EXISTS novel;

CREATE TABLE novel (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    ndate TEXT NOT NULL,
    ntype TEXT NOT NULL,
    link TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);